### ISSUE TITLE
Experiencing "NET::ERR_CERT_COMMON_NAME_INVALID" errors

### ISSUE THREAD

**Issue by MikeRosTX** [christianezeani/panthera-jekyll#2]
**Is your feature request related to a problem? Please describe.**
While setting up a GitHub Page using a **Custom domain** name on GoDaddy,com, I kept getting the following "**NET::ERR_CERT_COMMON_NAME_INVALID**" errors intermittently:

![image](https://user-images.githubusercontent.com/11631454/85316237-0e7c5980-b482-11ea-9a16-7f6a4aa8bf71.png)

**Describe the solution you'd like**
While researching this issue a bit more in-depth, I stumbled across this GitHub troubleshooter to secure an https site:

https://help.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https#resolving-problems-with-mixed-content

**Describe alternatives you've considered**
So it looks like the resolution was to replace all the **_http_** references for **_https_** on 120 files on my own repo. You may need to consider changing these references on the template so that GitHub Page can **Enforce HTTPS** on **Custom domains**.

https://github.com/MikeRosTX/mikerostx.github.io/commit/af28cdd7123e9f30f881011acdc665ce48a7b56c

![image](https://user-images.githubusercontent.com/11631454/85317337-d9710680-b483-11ea-9a02-4d7f619f47e9.png)

**Comment by MikeRosTX** [comment]
Well I thought that I had resolved these intermittent errors "**NET::ERR_CERT_COMMON_NAME_INVALID**" by replacing **_http_** with **_https_** on 120 files, but intermittent errors are sill occurring. I'm back to the drawing board of troubleshooting.

![image](https://user-images.githubusercontent.com/11631454/85355958-537cac00-b4d3-11ea-89f9-fc73978e1f70.png)

**Comment by MikeRosTX** [comment]
Not sure if this helped or not, but as soon as I added it I noticed that it immediately started working, 🤔  I'll continue monitoring.

![image](https://user-images.githubusercontent.com/11631454/85356941-df8fd300-b4d5-11ea-8dd4-d32b901f5438.png)

**Comment by christianezeani** [comment]
Hi @MikeRosTX 

It looks like you're experiencing issues that have to do with SSL misconfiguration. I just checked your site's info and saw that the SSL Certificate was issued to `shortener.secureserver.net` - that is why you're getting the `NET::ERR_CERT_COMMON_NAME_INVALID` error. The links below might be useful:

- https://uk.godaddy.com/community/SSL-And-Security/SSL-for-a-forwarded-domain/td-p/148378

For more info on the above error, visit:

- https://www.ssl2buy.com/wiki/how-to-fix-err_cert_common_name_invalid-in-chrome

NB: It might take a couple of hours for changes to reflect on your browser

**Comment by MikeRosTX** [comment]
Thanks @christianezeani!  I've already tried everything mentioned in the 2nd link from www.ssl2buy.com.
Following thee article from GoDaddy, I changed the TTL in the red box from 600 seconds to 1 hour. The first IP 184.168.131.241 is fixed by GoDaddy. The 4 IPs 185.199.x.x are GittHub Pages IPs. I'll keep monitoring. But in order for GitHub Pages to **Enforce HTTPS** every reference in the code has to be https.
![image](https://user-images.githubusercontent.com/11631454/85481115-d6127380-b586-11ea-9d40-3667d087e697.png)

**Comment by christianezeani** [comment]
Alright @MikeRosTX. I'll make those changes asap

**Comment by MikeRosTX** [comment]
Deleted the Forwarding piece below from DNS Management on GoDaddy, and left A and CNAME records. So far it seems to be working better. I'll continue to monitor this issue.

![image](https://user-images.githubusercontent.com/11631454/85498081-a83c2780-b5a4-11ea-8d20-f06145b81721.png)

**Comment by christianezeani** [comment]
Changed `http` references to `https`. These changes were made to the template files, 3rd party libraries were (and should be) left untouched.

**Comment by MikeRosTX** [comment]
Looks like the "**NET::ERR_CERT_COMMON_NAME_INVALID**" errors was a combination of things:
1. `http` references needed to be changed to `https`, to allow GitHub Pages to **Enforce HTTPS**. 
2. The extra **A** and **CNAME** records on GoDaddy.com that were removed.
3. Also the Forwarding of domain name at the bottom of GoDaddy.com DNS Management that was removed so it doesn't forward any domain names to GitHub Pages.

The "**NET::ERR_CERT_COMMON_NAME_INVALID**" errors has not reoccurred in several days.

**Comment by christianezeani** [comment]
Nice to hear that.
