### ISSUE TITLE
Feature Request - Return to home page

### ISSUE THREAD

**Issue by MikeRosTX** [christianezeani/panthera-jekyll#3]
**Describe the solution you'd like**
Ability to click on the avatar jpg either on the header or left pane, and it returns you to the index page.

**Comment by christianezeani** [comment]
Avatar on the left side now linking to site's base url

**Comment by MikeRosTX** [comment]
Thanks for this update! Works well.

**Question**: Is it possible to get the avatar on the right side in the header to link back to base url as well?
Reason I'm asking for this request, is that the left side avatar would be for linking back to base url from the desktop. 

But having the ability to click on the right side avatar in the header from a mobile device is one less click to take you back to the base url.

**Comment by christianezeani** [comment]
Ok. I'll link the avatar on the header to base url

**Comment by christianezeani** [comment]
Hi @MikeRosTX. Header avatar is now linked to base URL.

**Comment by MikeRosTX** [comment]
> Hi @MikeRosTX. Header avatar is now linked to base URL.

Just merge the new changes, and the Header avatar is not linking back Home base URL.

**Comment by christianezeani** [comment]
It's working here: https://christianezeani.github.io/panthera-jekyll/

Did resolve any merge conflict?

**Comment by MikeRosTX** [comment]
Yes, merge conflicts were resolved. See my page at https://mikerostx.me.
When clicking on both avatars (left pane & top right header) it should take me back to the home page URL (https://mikerostx.me) and it is not.

**Comment by christianezeani** [comment]
Issue resolved
