### ISSUE TITLE
Feature Request - Blog Post area

### ISSUE THREAD

**Issue by MikeRosTX** [christianezeani/panthera-jekyll#4]
**Is your feature request description. Please describe.**
Have a short cut link labeled **Blog Posts** in the left pane.

**Describe the solution you'd like**
Having a short cut link labeled **Blog Posts** in the left pane that will display list of blogs in the right pane. Then in the right pane, have a summary list of all the posts with a thumbnail that when clicking on it drills into the post.

EXAMPLE:  http://artemsheludko.com/flexible-jekyll/

**Describe alternatives you've considered**
Open to any other alternatives you can think of as a solution.

**Additional context**
![image](https://user-images.githubusercontent.com/11631454/85933513-79bc9600-b89d-11ea-84b0-43146db81659.png)

**Comment by MikeRosTX** [comment]
@christianezeani, I'm not in any hurry. But do you have an estimate on when you  might have this done? Just curious.

**Comment by christianezeani** [comment]
Hi @MikeRosTX . I'm sorry for the late response. This should be resolved in about 7 days.

**Comment by MikeRosTX** [comment]
Was just looking for an estimate, so I can stat gathering my thoughts on which blogs I want to bring over. So 7 days is 👍

**Comment by MikeRosTX** [comment]
> Hi @MikeRosTX . I'm sorry for the late response. This should be resolved in about 7 days.

7 days? 😉

**Comment by christianezeani** [comment]
> > Hi @MikeRosTX . I'm sorry for the late response. This should be resolved in about 7 days.
> 
> 7 days?

I'm sorry for the delay. I've been experiencing power failure lately. This has always been an issue though, but it got worse recently. Please give me 3 more days so I can clear up the tasks at hand and implement this feature.

**Comment by christianezeani** [comment]
Hi @MikeRosTX. The blog posts feature has been added, more info added to the `README` file.

A demo can be found here: [Panthera-Jekyll](//christianezeani.github.io/panthera-jekyll/). Contents of this demo can be found in the `docs` folder.

The following features will be added starting from version `1.4` (hopefully, 10 days from now):

* Related posts
* Post tags
* Disqus comment
* Share post via social media

**Comment by christianezeani** [comment]
Reopening for additional features

**Comment by MikeRosTX** [comment]
Images not being displayed from **_/docs/assets/images/name.jpg_**.
Had to use **_/assets/images/name.jpg_**.

**Comment by christianezeani** [comment]
Images should be in `/assets/` folder. The docs folder contains the files for https://christianezeani.github.io/panthera-jekyll/

**Comment by MikeRosTX** [comment]
> Images should be in `/assets/` folder. The docs folder contains the files for https://christianezeani.github.io/panthera-jekyll/

👍

**Comment by christianezeani** [comment]
Hi @MikeRosTX. I appears the `site.baseurl` variable wasn't working with custom domain. I just made some changes, you can view changes on https://christianezeani.github.io/panthera-jekyll/.

Kindly update your site and check if the issue has been resolved.

**Comment by MikeRosTX** [comment]
AWESOME! Issue **#3 Resolved**! 👍

**Comment by christianezeani** [comment]
> AWESOME! Issue **#3 Resolved**! 👍

Oh! I replied to the wrong issue
